name: day12_login
description: A new Flutter project.

version: 1.0.0+3

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  cupertino_icons: ^1.0.2
  animate_do:
  provider:
  path_provider:
  responsive_sizer:
  animated_search_bar:
  intl:
  http:
  motion_tab_bar:
  dropdown_button2:
  flutter_zoom_drawer:
  carousel_slider: ^5.0.0
  flutter_custom_carousel_slider: ^1.2.0
  rating_summary: ^1.0.2+1
  flutter_rating_bar: ^4.0.0
  google_maps_flutter: ^2.1.1
  rename: ^3.0.2
  url_launcher: ^6.0.20

  hive:
  hive_flutter:
  flutter_datetime_picker:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  change_app_package_name: ^1.3.0

flutter_icons:
  android: true
  image_path: assets/images/icon_logo.png
  android_adaptive_icon_background: "#ffffff"
  android_adaptive_icon_foreground: "assets/images/icon_logo.png"
  launcher_name: "Mawgood"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  # - images/a_dot_ham.jpeg
